### ISSUE TITLE
Installation instructions for Archlinux

### ISSUE THREAD

**Issue by cristobaltapia** [BarbieCue/ktgen#121]
Hi @BarbieCue
thanks for the nice project! I have packed it for Archlinux [here](https://aur.archlinux.org/packages/ktgen) and thought that you could add the respective instructions to install it, e.g.:

```
yay -S ktgen
```

Cheers!

**Comment by BarbieCue** [comment]
Hi @cristobaltapia 
thanks for your work! I'll check it in more detail soon and give you feedback.

Cheers!

**Comment by cristobaltapia** [comment]
Thanks, feedback would be great! I followed the [Java pacakge guidelines](https://wiki.archlinux.org/title/Java_package_guidelines) for Archlinux as best as I could, but this was my first time packaging a java app. At least it works, but any comments are welcome.

**Comment by BarbieCue** [comment]
Hi @cristobaltapia, at first sorry for that late response and again thanks for your Contribution. Two things need to be handled in more detail.

**1. Java Runtime Version**

Like described in the [Java Package Guidelines](https://wiki.archlinux.org/title/Java_package_guidelines) java-runtime needs to be a dependency and you defined it as dependency. That is fine. 

Difficulty: there is no constraint on a specific version. What if the user has java-runtime installed, but e.g. version 11 and not 17 or above?. ktgen is compiled against java 17 and thus requires that the user has at least java runtime 17 or higher?

**Idea:** we extend the ktgen start script (/usr/bin/ktgen) in a way, that it shows a hint to the user, when the users current java version is lower than 17 and then exit.


**2. We need a deploy pipeline**

It's really very nice that you created an AUR account and publish ktgen in the current version 1.4.0 over it. But what happens when a new version of ktgen is published in github? For example release 1.5.0? Then you would have to deploy it manually to the AUR. 

**Idea:** I create an AUR account and you delete yours, we create a github deploy pipeline that builds and deploys the AUR package "on release". The pipeline uses my AUR credentials so the latest version of ktgen is always published automatically (not manually).

**Comment by cristobaltapia** [comment]
Hi @BarbieCue , thanks for your feedback! 

> 1. Java Runtime Version
> 
> Like described in the [Java Package Guidelines](https://wiki.archlinux.org/title/Java_package_guidelines) java-runtime needs to be a dependency and you defined it as dependency. That is fine.
> 
> Difficulty: there is no constraint on a specific version. What if the user has java-runtime installed, but e.g. version 11 and not 17 or above?. ktgen is compiled against java 17 and thus requires that the user has at least java runtime 17 or higher?
>
> Idea: we extend the ktgen start script (/usr/bin/ktgen) in a way, that it shows a hint to the user, when the users current java version is lower than 17 and then exit.

Yes, I realized that. I was also not sure what was the best option to handle this. Actually, I also tried compiling with java version 20, but got errors. It worked however with version 17. I think that the idea with modifying the start script could work, but I am not an expert in java really :P 

> 2. We need a deploy pipeline
> 
> It's really very nice that you created an AUR account and publish ktgen in the current version 1.4.0 over it. But what happens when a new version of ktgen is published in github? For example release 1.5.0? Then you would have to deploy it manually to the AUR.
> 
> Idea: I create an AUR account and you delete yours, we create a github deploy pipeline that builds and deploys the AUR package "on release". The pipeline uses my AUR credentials so the latest version of ktgen is always published automatically (not manually).
> 

The normal approach is that the responsible person (maintainer) should do this manually. However I couldn't find anything in the arch wiki that suggests that automatizing this is not allowed. It is not necessary for me to delete my account, as I maintain other packages too. I can simply disown the package and then you can adopt it with your AUR account.

**Comment by BarbieCue** [comment]
> I can simply disown the package and then you can adopt it with your AUR account.

This is a good idea, let's do so. My account is _BarbieCue_. Can you transfer the ownership to me?

> Yes, I realized that. I was also not sure what was the best option to handle this. Actually, I also tried compiling with java version 20, but got errors. It worked however with version 17. I think that the idea with modifying the start script could work, but I am not an expert in java really :P

Ok, i have a plan and proceed when i'm the package owner. I'll notify you to show you a possible solution. :-)

**Comment by cristobaltapia** [comment]
Hi,

I have disown the package, so you can adopt it now ;)

https://aur.archlinux.org/packages/ktgen

**Comment by BarbieCue** [comment]
Thank you very much! I'll suggest a solution to you in the next days. And again: thanks for your interest and your contribution to ktgen! :)

**Comment by BarbieCue** [comment]
Hi @cristobaltapia 

after thinking about this topic for a while, I came to the conclusion that ktgen should primarily be executed by users via Docker. Only developers should run ktgen via Java. With this in mind, I would no longer want to offer an AUR package for ktgen (with Java as a dependency).

Thank you very much for your idea, it has finally provided more clarity. :)

**Comment by BarbieCue** [comment]
If it's okay with you, I would suggest closing this issue accordingly. @cristobaltapia

**Comment by cristobaltapia** [comment]
Hi @BarbieCue 

thanks for taking your time to consider this. I don't have any problems with docker, but personally prefer not to use it for desktop utilities. You absolutely don't need to provide support for the AUR package. Actually, most of the packagers are not the developers of the respective app. Therefore I don't see any problem in the AUR package to exist for anyone who would like to install ktgen that way. I can take care of it if you wish to disown it ;)

Closing this issue.
